# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisName', models.CharField(max_length=200, verbose_name='fisName')),
                ('secName', models.CharField(blank=True, max_length=200, verbose_name='secName')),
                ('login', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phoneNumber')),
            ],
        ),
    ]
